"""Provision a remote (Render) PostgreSQL database for the read-only public API.

Equivalent to ``scripts/local_stack.py bootstrap-db`` minus docker compose and minus every
worker/scorer role: only the API reader and the release publisher get login roles.

    PCB_RENDER_DATABASE_URL=<external owner connection string> \
        uv run --locked --all-packages python scripts/render/bootstrap_remote.py

Steps (all idempotent): preflight the owner's privileges, ``provision_roles.sql``, ``alembic
upgrade head`` (runs as ``SET ROLE pcb_migrator``), ``grant_permissions.sql``, then login roles
``pcb_render_api`` (member of ``pcb_public_reader`` only) and ``pcb_render_publisher`` (member of
``pcb_publisher`` only). Generated credentials go to ``.local/render/render-secrets.env`` (mode
600, git-ignored) and are reused on re-runs; nothing secret is printed.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SQL_DIR = ROOT / "packages" / "persistence" / "sql"
ALEMBIC_INI = ROOT / "packages" / "persistence" / "alembic.ini"
DEFAULT_SECRETS_FILE = ROOT / ".local" / "render" / "render-secrets.env"
API_ROLE = "pcb_render_api"
PUBLISHER_ROLE = "pcb_render_publisher"
ROLE_NAME = re.compile(r"^[a-z][a-z0-9_]{0,62}$")
LOCAL_HOSTS = {"localhost", "127.0.0.1", "::1", "host.docker.internal"}


def _url(raw: str) -> Any:
    from sqlalchemy.engine import make_url

    url = make_url(raw)
    if url.get_backend_name() != "postgresql":
        raise SystemExit("PCB_RENDER_DATABASE_URL must be a postgresql:// connection string")
    url = url.set(drivername="postgresql+psycopg")
    host = url.host or ""
    if host not in LOCAL_HOSTS and "sslmode" not in url.query:
        url = url.update_query_dict({"sslmode": "require"})
    return url


def internal_host(external_host: str) -> str:
    """Render's internal hostname is the external one without the region suffix."""
    if external_host.endswith(".render.com") and "." in external_host:
        return external_host.split(".", 1)[0]
    return external_host


def _conninfo(url: Any) -> str:
    return str(url.set(drivername="postgresql").render_as_string(hide_password=False))


def read_secrets(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            name, sep, value = line.partition("=")
            if sep and name and not name.startswith("#"):
                values[name] = value
    return values


def write_secrets(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "# Generated by scripts/render/bootstrap_remote.py. Contains secrets; never commit.\n"
    body += "".join(f"{name}={value}\n" for name, value in values.items())
    path.write_text(body, encoding="utf-8", newline="\n")
    try:
        path.chmod(0o600)
    except OSError:
        pass


def build_secrets(url: Any, existing: dict[str, str]) -> dict[str, str]:
    """Return the credential set; passwords and keys already generated are kept."""
    api_password = existing.get("PCB_RENDER_API_PASSWORD") or secrets.token_urlsafe(32)
    publisher_password = existing.get("PCB_RENDER_PUBLISHER_PASSWORD") or secrets.token_urlsafe(32)
    cursor_key = existing.get("PCB_CURSOR_SIGNING_KEY") or secrets.token_hex(32)
    database = url.database

    def dsn(role: str, password: str, host: str) -> str:
        rendered = url.set(username=role, password=password, host=host)
        return str(rendered.render_as_string(hide_password=False))

    external = url.host or ""
    internal = internal_host(external)
    return {
        "PCB_RENDER_API_PASSWORD": api_password,
        "PCB_RENDER_PUBLISHER_PASSWORD": publisher_password,
        "PCB_CURSOR_SIGNING_KEY": cursor_key,
        # Set on the pcb-api Render service (same-region internal hostname).
        "PCB_DATABASE_URL": dsn(API_ROLE, api_password, internal),
        # Used on this PC by scripts/render/publish_remote.py (external hostname).
        "PCB_RENDER_PUBLISHER_DATABASE_URL": dsn(PUBLISHER_ROLE, publisher_password, external),
        "PCB_RENDER_API_DATABASE_URL_EXTERNAL": dsn(API_ROLE, api_password, external),
        "PCB_RENDER_DATABASE_NAME": str(database),
    }


def _run_script(conn: Any, path: Path) -> None:
    conn.execute(path.read_text(encoding="utf-8"))  # type: ignore[arg-type]


def preflight(conn: Any) -> dict[str, Any]:
    row = conn.execute(
        "SELECT current_user, current_database(), r.rolsuper, r.rolcreaterole, "
        "current_setting('server_version_num')::int "
        "FROM pg_roles r WHERE r.rolname = current_user"
    ).fetchone()
    user, database, superuser, createrole, version = row
    if not (superuser or createrole):
        raise SystemExit(
            "the database owner can neither create roles nor is a superuser; PolyCodeBench "
            "needs its group roles (see packages/persistence/sql/provision_roles.sql). Use a "
            "different Render database plan/provider or run the SQL as an administrator."
        )
    if version < 140000:
        raise SystemExit("PostgreSQL 14 or newer is required")
    return {
        "user": user,
        "database": database,
        "superuser": bool(superuser),
        "createrole": bool(createrole),
        "server_version_num": version,
    }


def _quote_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def ensure_login_role(conn: Any, role: str, password: str, group: str, database: str) -> None:
    if not ROLE_NAME.match(role) or not ROLE_NAME.match(group):
        raise ValueError("invalid role name")
    exists = conn.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (role,)).fetchone()
    if exists is None:
        conn.execute(f"CREATE ROLE {role} LOGIN")  # type: ignore[arg-type]
    # ALTER ROLE ... PASSWORD cannot take bind parameters; escape as a literal.
    conn.execute(f"ALTER ROLE {role} WITH LOGIN PASSWORD {_quote_literal(password)}")  # type: ignore[arg-type]
    # Exactly one group: drop any other pcb_* membership an earlier run may have granted.
    conn.execute(
        "DO $$ DECLARE g text; BEGIN FOR g IN SELECT b.rolname FROM pg_auth_members m "
        "JOIN pg_roles b ON b.oid = m.roleid JOIN pg_roles r ON r.oid = m.member "
        f"WHERE r.rolname = '{role}' AND b.rolname <> '{group}' LOOP "
        f"EXECUTE format('REVOKE %I FROM {role}', g); END LOOP; END $$"  # type: ignore[arg-type]
    )
    conn.execute(f"GRANT {group} TO {role}")  # type: ignore[arg-type]
    quoted_db = '"' + database.replace('"', '""') + '"'
    conn.execute(f"GRANT CONNECT ON DATABASE {quoted_db} TO {role}")  # type: ignore[arg-type]


def migrate(url: Any) -> None:
    from alembic.config import main as alembic_main

    os.environ["PCB_MIGRATION_DATABASE_URL"] = url.render_as_string(hide_password=False)
    status = alembic_main(argv=["-c", str(ALEMBIC_INI), "upgrade", "head"])
    if status:
        raise SystemExit("alembic upgrade head failed")


def bootstrap(raw_url: str, secrets_file: Path, *, skip_migrations: bool = False) -> dict[str, Any]:
    import psycopg

    url = _url(raw_url)
    credentials = build_secrets(url, read_secrets(secrets_file))
    with psycopg.connect(_conninfo(url), autocommit=True) as conn:
        report = preflight(conn)
        database = report["database"]
        _run_script(conn, SQL_DIR / "provision_roles.sql")
        if not report["superuser"]:
            # CREATE ROLE gives the creator ADMIN only; the migrator needs SET to SET ROLE.
            conn.execute(f"GRANT pcb_migrator TO {_ident(report['user'])} WITH SET TRUE")  # type: ignore[arg-type]
    if not skip_migrations:
        migrate(url)
    with psycopg.connect(_conninfo(url), autocommit=True) as conn:
        _run_script(conn, SQL_DIR / "grant_permissions.sql")
        ensure_login_role(
            conn, API_ROLE, credentials["PCB_RENDER_API_PASSWORD"], "pcb_public_reader", database
        )
        ensure_login_role(
            conn,
            PUBLISHER_ROLE,
            credentials["PCB_RENDER_PUBLISHER_PASSWORD"],
            "pcb_publisher",
            database,
        )
    write_secrets(secrets_file, credentials)
    return {
        **report,
        "login_roles": [API_ROLE, PUBLISHER_ROLE],
        "migrations": "skipped" if skip_migrations else "head",
        "secrets_file": str(secrets_file),
    }


def _ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--secrets-file", type=Path, default=DEFAULT_SECRETS_FILE)
    parser.add_argument("--skip-migrations", action="store_true")
    parser.add_argument("--verbose", action="store_true", help="print the error message too")
    args = parser.parse_args(argv)
    raw = os.environ.get("PCB_RENDER_DATABASE_URL")
    if not raw:
        print(
            "PCB_RENDER_DATABASE_URL is required (the Render owner connection string).",
            file=sys.stderr,
        )
        return 2
    try:
        report = bootstrap(raw, args.secrets_file, skip_migrations=args.skip_migrations)
    except SystemExit:
        raise
    except Exception as error:  # driver text can carry the DSN; print only the type
        detail = f": {str(error)[:300]}" if args.verbose else ""
        print(f"bootstrap failed: {type(error).__name__}{detail}", file=sys.stderr)
        return 1
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
