#!/usr/bin/env bash
# Run ON the Oracle A1 VM (as the deploy user, over SSH) before starting the PolyCodeBench POC.
#
# - checks the host is arm64 and Docker + compose are present
# - generates random credentials into a root-only file OUTSIDE the repository
#   (default /etc/pcb/poc.env, mode 600); it mirrors the keys that
#   scripts/local_stack.py `prepare` expects, so the loopback stack can use them
# - never prints a secret value
#
# Usage: bootstrap-poc.sh [--force]
#   --force  replace an existing secrets file (new credentials; existing volumes will not match)
set -euo pipefail

POC_ENV_DIR="${PCB_POC_ENV_DIR:-/etc/pcb}"
POC_ENV_FILE="${POC_ENV_DIR}/poc.env"
FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

[ "$(uname -m)" = "aarch64" ] || fail "expected an aarch64 (arm64) host, found $(uname -m)"
command -v docker >/dev/null 2>&1 || fail "docker is not installed (cloud-init may still be running; check /var/log/cloud-init-output.log)"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin is not available"
command -v openssl >/dev/null 2>&1 || fail "openssl is not installed"
if [ "$(id -u)" -ne 0 ]; then
  command -v sudo >/dev/null 2>&1 || fail "run as root or install sudo"
  SUDO="sudo"
else
  SUDO=""
fi

if $SUDO test -e "$POC_ENV_FILE" && [ "$FORCE" -ne 1 ]; then
  echo "Secrets file already exists at ${POC_ENV_FILE}; leaving it unchanged (use --force to replace)."
else
  umask 077
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT

  token() { openssl rand -base64 48 | tr '+/' '-_' | tr -d '=\n' | cut -c1-43; }
  hexkey() { openssl rand -hex 32; }

  api_pw="$(token)"
  publisher_pw="$(token)"
  pg_pw="$(token)"
  worker_pw="$(token)"
  scorer_pw="$(token)"
  db="pcb_local_web_test"
  ops_db="pcb_ops_rehearsal_source"
  host="127.0.0.1:55432"

  {
    echo "# Generated by bootstrap-poc.sh on this host. Synthetic-data POC only. Do not copy off the VM."
    echo "KEYCLOAK_ADMIN_USERNAME=pcb-local-admin"
    echo "KEYCLOAK_ADMIN_PASSWORD=$(token)"
    echo "LOCAL_SUBMITTER_USERNAME=local-submitter"
    echo "LOCAL_SUBMITTER_EMAIL=local-submitter@example.test"
    echo "LOCAL_SUBMITTER_PASSWORD=$(token)"
    echo "LOCAL_REVIEWER_TOKEN=$(token)"
    echo "PCB_WEB_AUTH_SIGNING_KEY=$(hexkey)"
    echo "PCB_CURSOR_SIGNING_KEY=$(hexkey)"
    echo "PCB_LOCAL_API_PASSWORD=${api_pw}"
    echo "PCB_LOCAL_WORKER_PASSWORD=${worker_pw}"
    echo "PCB_LOCAL_SCORER_PASSWORD=${scorer_pw}"
    echo "PCB_LOCAL_POSTGRES_PASSWORD=${pg_pw}"
    echo "PCB_LOCAL_S3_ACCESS_KEY=$(token | cut -c1-32)"
    echo "PCB_LOCAL_S3_SECRET_KEY=$(token)"
    echo "PCB_DATABASE_URL=postgresql+psycopg://pcb_local_api:${api_pw}@${host}/${db}"
    echo "PCB_PUBLISHER_DATABASE_URL=postgresql+psycopg://pcb_local_publisher:${publisher_pw}@${host}/${db}"
    echo "PCB_MIGRATION_DATABASE_URL=postgresql+psycopg://polycodebench:${pg_pw}@${host}/${db}"
    echo "PCB_WORKER_DATABASE_URL=postgresql+psycopg://pcb_local_worker:${worker_pw}@${host}/${db}"
    echo "PCB_SCORER_DATABASE_URL=postgresql+psycopg://pcb_local_scorer:${scorer_pw}@${host}/${db}"
    echo "PCB_OPS_REHEARSAL_DATABASE_URL=postgresql+psycopg://polycodebench:${pg_pw}@${host}/${ops_db}"
    echo "PCB_OBJECT_STORE_ENDPOINT=http://127.0.0.1:8333"
    echo "PCB_OBJECT_STORE_PROVIDER=s3"
    echo "PCB_OBJECT_STORE_REGION=us-east-1"
    echo "PCB_OBJECT_STORE_ADDRESSING_STYLE=path"
    echo "PCB_BUCKET_HIDDEN=pcb-hidden-local"
    echo "PCB_BUCKET_INTERNAL=pcb-internal-local"
    echo "PCB_BUCKET_PUBLIC=pcb-public-local"
    echo "PCB_PUBLIC_RELEASE_BACKEND=postgres"
    echo "PCB_PUBLICATION_TARGET=local:board"
    echo "PCB_RELEASE_STORE_PATH=.cache/polycodebench-local-release-store.sqlite3"
    echo "PCB_OIDC_ISSUER=http://127.0.0.1:8080/realms/polycodebench-local"
    echo "PCB_OIDC_CLIENT_ID=polycodebench-web"
    echo "PCB_OIDC_REDIRECT_URI=http://127.0.0.1:3001/auth/callback"
    echo "PCB_WEB_ORIGIN=http://127.0.0.1:3001"
    echo "PCB_PUBLIC_API_URL=http://127.0.0.1:8010/v1"
    echo "PCB_API_IDENTITY_FILE=.cache/polycodebench-local-identities.json"
    echo "PCB_ENVIRONMENT=dev"
    echo "PCB_SERVICE_IDENTITY=polycodebench-local-development"
    echo "PCB_LOCAL_WORKER_SETUP_ENABLED=false"
    echo "PCB_WORKER_DISPATCH_ENABLED=false"
    echo "PCB_LOCAL_SCORING_ENABLED=false"
  } >"$tmp"

  $SUDO install -d -m 700 -o root -g root "$POC_ENV_DIR"
  $SUDO install -m 600 -o root -g root "$tmp" "$POC_ENV_FILE"
  echo "Wrote ${POC_ENV_FILE} (root-only, mode 600) with $(grep -c '=' "$tmp") generated settings. Values were not printed."
fi

cat <<EOF

Next steps (from the repository checkout on this VM):
  1. Install the file as the repo's ignored .env, readable only by you:
       sudo install -m 600 -o "\$USER" ${POC_ENV_FILE} .env
  2. Follow docs/operations/oracle-poc-runbook.md from "Prepare and start the stack".
  Keep every listener on 127.0.0.1; reach the UI only through the SSH tunnel.
EOF
