#!/usr/bin/env bash
# Run on the operator workstation (Git Bash on Windows works). Generates the ignored
# terraform.tfvars for a public HTTPS A1 VM and runs Terraform in a pinned container with the
# owner's ~/.oci profile mounted read-only.
#
# Usage:
#   scripts/oracle/provision.sh tfvars [--compartment <ocid>] [--ad-index N]
#   scripts/oracle/provision.sh plan | apply | output | destroy | apply-destroy
#
# Nothing is created by `tfvars` or `plan`. `apply` only applies the saved plan file.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TF_DIR="$ROOT/infra/oracle/terraform"
OCI_DIR="${OCI_CONFIG_DIR:-$HOME/.oci}"
PUBKEY="$ROOT/.local/oracle/pcb_deploy_ed25519.pub"
TF_IMAGE="hashicorp/terraform:1.13"

to_docker_path() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi
}

terraform_run() {
  MSYS_NO_PATHCONV=1 docker run --rm -i \
    -v pcb-tf-plugin-cache:/plugins -e TF_PLUGIN_CACHE_DIR=/plugins \
    -v "$(to_docker_path "$ROOT/infra"):/infra" \
    -v "$(to_docker_path "$OCI_DIR"):/root/.oci:ro" \
    -w /infra/oracle/terraform "$TF_IMAGE" "$@"
}

oci_value() { # oci_value <key> from the DEFAULT profile
  awk -F'=' -v key="$1" '
    /^\[/ { in_default = ($0 == "[DEFAULT]") }
    in_default && $1 ~ "^[[:space:]]*" key "[[:space:]]*$" { gsub(/[[:space:]]/, "", $2); print $2; exit }
  ' "$OCI_DIR/config"
}

case "${1:-}" in
  tfvars)
    shift
    compartment=""
    ad_index=0
    while [ $# -gt 0 ]; do
      case "$1" in
        --compartment) compartment="$2"; shift 2 ;;
        --ad-index) ad_index="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
      esac
    done
    [ -f "$OCI_DIR/config" ] || { echo "missing $OCI_DIR/config" >&2; exit 1; }
    [ -f "$PUBKEY" ] || { echo "missing $PUBKEY" >&2; exit 1; }
    region="$(oci_value region)"
    tenancy="$(oci_value tenancy)"
    key_file="$(oci_value key_file)"
    [ -n "$region" ] && [ -n "$tenancy" ] || { echo "OCI config lacks region/tenancy" >&2; exit 1; }
    case "$key_file" in
      "~/.oci/"*|"/root/.oci/"*) ;;
      *) echo "key_file in $OCI_DIR/config must be ~/.oci/<name>.pem so the container can read it" >&2; exit 1 ;;
    esac
    my_ip="$(curl -fsS https://api.ipify.org)"
    cat > "$TF_DIR/terraform.tfvars" <<EOF
# Generated by scripts/oracle/provision.sh (git-ignored). Always Free A1, public HTTPS.
owner_spend_acknowledged = true
home_region              = "${region}"
compartment_ocid         = "${compartment:-$tenancy}"
image_id                 = ""
access_mode              = "public_ssh"
public_web               = true
allowed_ssh_cidr         = "${my_ip}/32"
ssh_public_key           = "$(tr -d '\r\n' < "$PUBKEY")"
availability_domain_index = ${ad_index}
ocpus                    = 2
memory_in_gbs            = 12
boot_volume_size_in_gbs  = 100
EOF
    terraform_run fmt terraform.tfvars >/dev/null
    echo "Wrote $TF_DIR/terraform.tfvars (region ${region}, SSH from ${my_ip}/32)."
    ;;
  plan)
    terraform_run init -input=false -lockfile=readonly >/dev/null
    terraform_run plan -input=false -out=pcb-poc.tfplan
    ;;
  apply)
    [ -f "$TF_DIR/pcb-poc.tfplan" ] || { echo "run plan first" >&2; exit 1; }
    terraform_run apply -input=false pcb-poc.tfplan
    terraform_run output -no-color
    ;;
  output)
    terraform_run output -no-color
    ;;
  destroy)
    # Writes a destroy plan for review; apply it with: provision.sh apply-destroy
    terraform_run plan -destroy -input=false -out=pcb-poc-destroy.tfplan
    ;;
  apply-destroy)
    [ -f "$TF_DIR/pcb-poc-destroy.tfplan" ] || { echo "run destroy first" >&2; exit 1; }
    terraform_run apply -input=false pcb-poc-destroy.tfplan
    ;;
  *)
    sed -n '2,11p' "$0"
    exit 2
    ;;
esac
